name: Execute notebook

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'hyper-parameters.yaml'
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
        with:
          requirement_files: requirements.txt  # this is optional

      - uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

        # the package installation will only be executed when the
        # requirements-files have changed.
      - run: pip install -r requirements.txt
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      - uses: yaananth/run-notebook@v2
        env:
          RUNNER: ${{ toJson(runner) }}
          SECRETS: ${{ toJson(secrets) }}
          GITHUB: ${{ toJson(github) }}
        with:
          notebook: "healthcare_analytics_xgboost.ipynb"
          isReport: False
          poll: False
      - name: Run the Giskard Scan 🐢
        run: |
          output=$(python scan.py)
          echo "::set-output name=report_name::$output"
      - name: Upload report
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          mkdir -p reports
          mv report/* reports/.
          git add reports
          git commit -m "🤖 github-bot: Updated Reports"
          git push
      - name: PR comment
        uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: |
              Hi, this is a report generated by the Giskard Scan.

              We have identified potential vulnerabilities in your model based on an automated scan.
              
              However, it's important to note that automated scans may produce false positives or miss certain vulnerabilities. We encourage you to review the findings and assess the impact accordingly.
              
              Report summary
              
              [View full report](https://htmlpreview.github.io/?${{ github.server_url }}/${{ github.repository 
              }}/blob/main/reports/${{ steps.step7.outputs.report_name }}.html)